#version 450
#extension GL_GOOGLE_include_directive : enable
#include "checkerboard_filter.comp"
layout(local_size_x = 32, local_size_y = 16, local_size_z = 1) in;

void RedPixelFilter()
{
    ivec2 p = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
    if (gl_LocalInvocationID.x % 2 == 0) {
        p.y = p.y * 2 + 1;
    } else {
        p.y = p.y * 2;
    }

    CheckerboardFilter(p);
}

void main(){
    RedPixelFilter();
}
